version: '3.8'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/opt
    networks:
      - host
    links:
    - mongo
  mongo:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      - host
volumes:
  mongo-data:
  mongo-configdb:
  

networks:
    host: